---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.global.namespace }}
  name: momo-ingress
spec:
  ingressClassName: "nginx"
  tls:
  - secretName: sudouser-net
    hosts:
      - {{ .Values.hostname }}
  rules:
  - host: {{ .Values.hostname }}
    http: 
      paths: 
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: momo-frontend
            port: 
              number: 80