---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: momo-ingress
spec:
  ingressClassName: "nginx"
  tls:
  - secretName: sudouser-net
    hosts:
      - "momo.sudouser.net"
  rules:
  - host: "momo.sudouser.net"
    http: 
      paths: 
      - path: /  # Catches all paths
        pathType: Prefix
        backend:
          service:
            name: momo-frontend
            port: 
              number: 80