apiVersion: v1
kind: Secret
metadata:
  name: sudouser-net
  namespace: {{ .Values.global.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls-cert }} 
  tls.key: {{ .Values.tls-key }} 