include: include.gitlab-ci.yml

stages:
  - build
  - release
  - deploy

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  FOLDER: frontend
  SERVICE_NAME: frontend
  RELEASE_NAME: momo-frontend

frontend-build-job:
  stage: build
  extends: .container-build-routine

frontend-release-job:
  stage: release
  needs:
    - frontend-build-job
  extends: .container-release-routine

frontend-deploy-job:
  stage: deploy
  needs:
    - frontend-release-job
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /CD/ 
  extends: .helm-deploy-routine