
.container-build-routine:
  image: 
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - echo "version- ${VERSION}"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/${FOLDER}"
      --dockerfile "${CI_PROJECT_DIR}/${FOLDER}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/${RELEASE_NAME}:${VERSION}"
      --build-arg VERSION=$VERSION
      --cache=true

.container-release-routine:
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/${RELEASE_NAME}:${VERSION} latest

.helm-deploy-routine:
  image:
    name: alpine/helm:3.14.4
    entrypoint: [ "sh" ]
  script:
    - apk add aws-cli
    - aws eks --region ${AWS_REGION} update-kubeconfig 
      --name ${EKS_CLUSTER_NAME} --role-arn ${EKS_ROLE_ARN}
    - helm upgrade --install --atomic --namespace ${PROD_NAMESPACE}
      --set regcreds=${REG_CREDS} 
      --set global.namespace=${PROD_NAMESPACE} 
      --set frontend.hostname=${PROD_DOMAIN} 
      --set frontend.tlskey=${TLS_KEY} 
      --set frontend.tlscert=${TLS_CERT} 
      --set ${SERVICE_NAME}.image=$CI_REGISTRY_IMAGE/${RELEASE_NAME}:${VERSION} 
      momo-store deploy/.