
.container-build-routine:
  image: 
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - echo "version- ${VERSION}"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/${FOLDER}"
      --dockerfile "${CI_PROJECT_DIR}/${FOLDER}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/${RELEASE_NAME}:${VERSION}"
      --build-arg VERSION=$VERSION
      --cache=true

.container-release-routine:
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/${RELEASE_NAME}:${VERSION} latest

.helm-deploy-routine:
  image:
    name: alpine/helm:3.14.4
    entrypoint: [ "sh" ]
  script:
    - mkdir /root/.kube
    - echo '${KUBECONFIG}' > /root/.kube/config 
    - chmod 700 -R /root/.kube
    - helm upgrade --install --atomic
      --set ${SERVICE_NAME}.image=$CI_REGISTRY_IMAGE/${RELEASE_NAME}:${VERSION} 
      momo-store deploy/.
    - rm /root/.kube/config 