include: include.gitlab-ci.yml

stages:
  - build
  - release
  - deploy

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  FOLDER: backend
  SERVICE_NAME: backend
  RELEASE_NAME: momo-backend

backend-build-job:
  stage: build
  extends: .container-build-routine

backend-release-job:
  stage: release
  needs:
    - backend-build-job
  extends: .container-release-routine

backend-deploy-job:
  stage: deploy
  needs:
    - backend-release-job
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /CD/ 
  extends: .helm-deploy-routine 
  