stages:
  - deploy

deploy-helm-job:
  stage: deploy
  image:
    name: alpine/helm:3.14.4
    entrypoint: [ "sh" ]
  script:
    - mkdir /root/.kube
    - echo '${KUBECONFIG}' > /root/.kube/config 
    - chmod 700 -R /root/.kube
    - helm upgrade --install --atomic momo-store deploy/.
    - rm /root/.kube/config 